on:
  push:
    branches: [ builds-experimental ]  # for development; change to master before merging
    tags: [ 'v*']

name: release

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15.3

    - name: Build binaries
      id: build
      run: go run build/build.go

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: Please add your release note here
          draft: true
          prerelease: false

    - name: Upload binaries
      id: upload_binaries 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.build.outputs.upload_url }} 
        asset_path: ./dnscontrol.exe
        asset_name: dnscontrol.exe
#        asset_content_type: application/zip
